rocksilencing/reagent_db/urls.py
from django.urls import path
from .views.reagent_db_views import reagent_db_page, calculate_consumption

app_name = "reagent_db"

urlpatterns = [
    path("", reagent_db_page, name="main"),
    path("calculate_consumption/", calculate_consumption, name="calculate_consumption"),
]

rocksilencing/rocksilencing/urls.py
# rocksilencing/urls.py

from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView  # Импорт RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="/files/", permanent=True)),
    path("calculator/", include("calculator.urls", namespace="calculator")),
    path("users/", include("users.urls", namespace="users")),
    path("files/", include("filesapp.urls", namespace="filesapp")),
    path("expert_systema/", include("expert_systema.urls", namespace="expert_systema")),
    path(
        "salt_calculator", include("salt_calculator.urls", namespace="salt_calculator")
    ),
    path("reagent_db/", include("reagent_db.urls", namespace="reagent_db")),
]

rocksilencing/users/urls.py
# users/urls.py

from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("register/done/", views.register_done, name="register_done"),
]

rocksilencing/reagent_db/models/reagent_db_models_heavy.py
from django.db import models


class WeightingAgent(models.Model):
    MATERIAL_TYPES = [
        ("Минерал", "Минерал"),
        ("Осадочная порода", "Осадочная порода"),
    ]

    name = models.CharField(max_length=255, verbose_name="Название")
    type = models.CharField(
        max_length=100, choices=MATERIAL_TYPES, verbose_name="Тип материала"
    )
    application = models.TextField(verbose_name="Применение")

    class Meta:
        verbose_name = "Утяжелитель"
        verbose_name_plural = "Утяжелители"

    def __str__(self):
        return self.name

rocksilencing/reagent_db/models/reagent_db_models_ingcorr.py
from django.db import models


class CorrosionInhibitor(models.Model):
    """Модель для ингибиторов коррозии"""

    name = models.CharField(max_length=255, verbose_name="Название")
    type = models.CharField(max_length=100, verbose_name="Тип")
    application = models.TextField(verbose_name="Применение")

    class Meta:
        verbose_name = "Ингибитор коррозии"
        verbose_name_plural = "Ингибиторы коррозии"

    def __str__(self):
        return self.name

rocksilencing/reagent_db/models/reagent_db_models_ingsalt.py
from django.db import models


class ScaleInhibitor(models.Model):
    """Модель для ингибиторов солеотложений"""

    name = models.CharField(max_length=255, verbose_name="Название")
    type = models.CharField(max_length=100, verbose_name="Тип")
    application = models.TextField(verbose_name="Применение")

    class Meta:
        verbose_name = "Ингибитор солеотложений"
        verbose_name_plural = "Ингибиторы солеотложений"

    def __str__(self):
        return self.name

rocksilencing/reagent_db/models/reagent_db_models_other.py
from django.db import models


class OtherMaterial(models.Model):
    MATERIAL_TYPES = [
        ("Базовая жидкость", "Базовая жидкость"),
        ("Специальная добавка", "Специальная добавка"),
        ("Химический реагент", "Химический реагент"),
    ]

    name = models.CharField(max_length=255, verbose_name="Название")
    type = models.CharField(max_length=100, choices=MATERIAL_TYPES, verbose_name="Тип")
    application = models.TextField(verbose_name="Применение")

    class Meta:
        verbose_name = "Прочий материал"
        verbose_name_plural = "Прочие материалы"

    def __str__(self):
        return self.name

rocksilencing/reagent_db/models/reagent_db_models_pavs.py
from django.db import models


class Surfactant(models.Model):
    PAV_TYPES = [
        ("Анионный ПАВ", "Анионный ПАВ"),
        ("Катионный ПАВ", "Катионный ПАВ"),
        ("Неионный ПАВ", "Неионный ПАВ"),
        ("Смесь анионных и катионных ПАВ", "Смесь анионных и катионных ПАВ"),
        ("Смесь анионных и неионнных ПАВ", "Смесь анионных и неионнных ПАВ"),
    ]

    name = models.CharField(max_length=255, verbose_name="Название")
    type = models.CharField(max_length=100, choices=PAV_TYPES, verbose_name="Тип ПАВ")
    application = models.TextField(verbose_name="Применение")

    class Meta:
        verbose_name = "ПАВ"
        verbose_name_plural = "ПАВ"

    def __str__(self):
        return self.name

rocksilencing/reagent_db/models/reagent_db_models_polymers.py
from django.db import models


class Polymer(models.Model):
    POLYMER_TYPES = [
        ("Водорастворимый полимер", "Водорастворимый полимер"),
        ("Природный полимер", "Природный полимер"),
        ("Биополимер", "Биополимер"),
        ("Синтетический полимер", "Синтетический полимер"),
    ]

    name = models.CharField(max_length=255, verbose_name="Название")
    type = models.CharField(
        max_length=100, choices=POLYMER_TYPES, verbose_name="Тип полимера"
    )
    application = models.TextField(verbose_name="Применение")

    class Meta:
        verbose_name = "Полимер"
        verbose_name_plural = "Полимеры"

    def __str__(self):
        return self.name

rocksilencing/reagent_db/models/reagent_db_models_reagentypes.py
from django.db import models


class ReagentType(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Тип реагента"
    )  # Название типа, например, "Прочее", "ПАВ", "Полимеры"
    description = models.TextField(
        verbose_name="Описание", blank=True, null=True
    )  # Краткое описание типа (опционально)

    class Meta:
        verbose_name = "Тип реагента"
        verbose_name_plural = "Типы реагентов"

    def __str__(self):
        return self.name

rocksilencing/reagent_db/models/reagent_db_models_salts.py
from django.db import models


class ReagentSalt(models.Model):
    name = models.CharField("Химическая формула", max_length=50)  # CaCl2, KCl и т.д.
    full_name = models.CharField("Полное название", max_length=100)
    description = models.TextField("Описание")

    def __str__(self):
        return f"{self.name} ({self.full_name})"

    class Meta:
        verbose_name = "Соль"
        verbose_name_plural = "Соли"


class ReagentSaltSolution(models.Model):
    salt = models.ForeignKey(
        ReagentSalt, on_delete=models.CASCADE, related_name="solutions"
    )
    density = models.FloatField("Плотность раствора, г/см³")
    salt_consumption = models.FloatField("Расход соли, кг/м³")
    water_consumption = models.FloatField("Расход воды, л/м³")
    viscosity = models.FloatField(
        "Вязкость, мПа·с", default=1.0
    )
    max_viscosity = models.FloatField(
        "Максимальная вязкость раствора, мПа·с", default=1.0
    )

    def __str__(self):
        return f"{self.salt.name} - {self.density} г/см³"

    class Meta:
        verbose_name = "Раствор соли"
        verbose_name_plural = "Растворы солей"
        ordering = ["salt", "density"]  # сортировка по соли и плотности

rocksilencing/reagent_db/views/reagent_db_views.py
import json
import json
import numpy as np

from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.db.models import Min, Max

from reagent_db.models.reagent_db_models_salts import ReagentSalt, ReagentSaltSolution
from reagent_db.models.reagent_db_models_ingcorr import CorrosionInhibitor
from reagent_db.models.reagent_db_models_pavs import Surfactant
from reagent_db.models.reagent_db_models_ingsalt import ScaleInhibitor
from reagent_db.models.reagent_db_models_heavy import WeightingAgent
from reagent_db.models.reagent_db_models_polymers import Polymer
from reagent_db.models.reagent_db_models_other import OtherMaterial

from collections import defaultdict
from random import choice
from scipy.interpolate import interp1d
from django.contrib.auth.decorators import login_required


# База реагентов


@login_required
def reagent_db_page(request):
    # Получаем все соли и их диапазоны плотностей
    bd_names_salts = ReagentSalt.objects.all().annotate(
        min_density=Min("solutions__density"), max_density=Max("solutions__density")
    )
    bd_all_solutions = ReagentSaltSolution.objects.all()
    bd_ingcorrs = CorrosionInhibitor.objects.all()
    bd_pavs = Surfactant.objects.all()
    bd_ingsalts = ScaleInhibitor.objects.all()
    bd_weights = WeightingAgent.objects.all()
    bd_polymers = Polymer.objects.all()
    bd_others = OtherMaterial.objects.all()

    # Преобразуем данные в формат JSON
    salts_json = json.dumps(list(bd_names_salts.values()), default=str)
    solutions_json = json.dumps(list(bd_all_solutions.values()), default=str)

    # Подготовка диапазонов плотностей
    ranges = {
        salt.id: {"min_density": salt.min_density, "max_density": salt.max_density}
        for salt in bd_names_salts
    }
    ranges_json = json.dumps(ranges, default=str)

    # Группируем решения по именам солей
    grouped_solutions = defaultdict(list)
    for sol in bd_all_solutions:
        grouped_solutions[sol.salt.name].append(sol)

    # Выбираем одно случайное решение для каждой соли
    random_solutions = {name: choice(sols) for name, sols in grouped_solutions.items()}

    return render(
        request,
        "reagent_db_page.html",
        {
            "bd_names_salts": bd_names_salts,
            "bd_all_solutions": bd_all_solutions,
            "bd_pavs": bd_pavs,  # Добавляем ПАВы
            "bd_ingcorrs": bd_ingcorrs,  # Добавляем ингибиторы коррозии
            "bd_ingsalts": bd_ingsalts,  # Добавляем ингибиторы солеотложений
            "bd_weights": bd_weights,
            "bd_polymers": bd_polymers,
            "bd_others": bd_others,
            "salts_json": salts_json,
            "solutions_json": solutions_json,
            "ranges_json": ranges_json,
            "random_solutions": random_solutions,
        },
    )


@login_required
def calculate_consumption(request):
    try:
        salt_id = int(request.GET.get("salt_id"))
        density = float(request.GET.get("density"))

        # Получаем все данные для указанной соли
        solutions = ReagentSaltSolution.objects.filter(salt_id=salt_id).order_by(
            "density"
        )

        if not solutions.exists():
            return JsonResponse(
                {"error": "No data found for the selected salt"}, status=404
            )

        # Подготовка данных для интерполяции
        densities = np.array([sol.density for sol in solutions])
        salt_consumptions = np.array([sol.salt_consumption for sol in solutions])
        water_consumptions = np.array([sol.water_consumption for sol in solutions])

        # Интерполяция
        salt_interp = interp1d(
            densities, salt_consumptions, kind="linear", fill_value="extrapolate"
        )
        water_interp = interp1d(
            densities, water_consumptions, kind="linear", fill_value="extrapolate"
        )

        # Вычисление значений
        salt_consumption = float(salt_interp(density))
        water_consumption = float(water_interp(density))
        return JsonResponse(
            {
                "salt_consumption": round(salt_consumption, 2),
                "water_consumption": round(water_consumption, 2),
            }
        )
    except ValueError:
        return JsonResponse({"error": "Invalid input data"}, status=400)
    except Exception as e:
        return JsonResponse({"error": str(e)}, status=500)

rocksilencing/reagent_db/templates/reagent_db_page.html
{% extends 'base.html' %} {% load static %} {% block styles %}
<link
	type="text/css"
	href="{%static 'css/reagent_db_page.css'%}"
	rel="stylesheet"
	crossorigin="anonymous"
/>
<title>База реагентов</title>
{% endblock %} {% block content %} {% csrf_token %}
<!-- header and sidebar ended-->

<script type="text/javascript">
	// Передаем данные в JavaScript
	const saltsData = JSON.parse('{{ salts_json|safe }}')
	const solutionsData = JSON.parse('{{ solutions_json|safe }}')
const calculateConsumptionURL = "{% url 'reagent_db:calculate_consumption' %}";
</script>
<script src="{%static 'js/reagent_db_page.js'%}" defer></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<main class="main__content">
	<section class="content__search">
<div class="tabs-wrapper">
    <div class="tabs-buttons">
        <select class="salt-select" name="salt-choose" id="salt-choose" placeholder="Выбор соли">
            <option>Выбор соли</option>
            {% for salt in bd_names_salts %}
                <option class="salt-option" data-target="{{ salt.name }}">{{ salt.name }}</option>
            {% endfor %}
        </select>
        <select class="salt-select" name="salt-base" id="salt-base" placeholder="Выбор базы">
            <option>Выбор базы</option>
            <option>База ПАВ</option>
            <option>База ингибиторов коррозии</option>
            <option>База ингибиторов солеотложений</option>
        </select>
    </div>

    <div class="tabs">
        <span class="tab on">
            <i class="bx bx-chevron-down"></i>
            Системные
        </span>

        <div class="inner-tabs on">
            <!-- Солевые растворы -->
            <span class="inner-tab on">
                <i class="bx bx-chevron-down"></i>
                Солевые растворы
            </span>
            <div class="tabs-items on">
                {% for salt in bd_names_salts %}
                    <span class="btn-salt" data-target="{{ salt.name }}">{{ salt.name }}</span>
                {% endfor %}
            </div>

            <!-- ПАВ -->
            <span class="inner-tab">
                <i class="bx bx-chevron-right"></i>
                 ПАВ
            </span>
            <div class="tabs-items">
                {% for pav in bd_pavs %}
                    <span class="btn" data-target="pav_{{ pav.id }}">{{ pav.name }}</span>
                {% endfor %}
            </div>

            <!-- Ингибиторы коррозии -->
            <span class="inner-tab">
                <i class="bx bx-chevron-right"></i>
                Ингибиторы коррозии
            </span>
            <div class="tabs-items">
                {% for ingcorr in bd_ingcorrs %}
                    <span class="btn" data-target="ingcorr_{{ ingcorr.id }}">{{ ingcorr.name }}</span>
                {% endfor %}
            </div>

            <!-- Ингибиторы солеотложений -->
            <span class="inner-tab">
                <i class="bx bx-chevron-right"></i>
                Ингибиторы солеотложений
            </span>
            <div class="tabs-items">
                {% for ingsalt in bd_ingsalts %}
                    <span class="btn" data-target="ingsalt_{{ ingsalt.id }}">{{ ingsalt.name }}</span>
                {% endfor %}
            </div>
			<!-- Утяжелители -->
            <span class="inner-tab">
                <i class="bx bx-chevron-right"></i>
                Утяжелители
            </span>
            <div class="tabs-items">
                {% for weight in bd_weights %}
                    <span class="btn" data-target="weight_{{ weight.id }}">{{ weight.name }}</span>
                {% endfor %}
            </div>
			<!-- Полимеры -->
            <span class="inner-tab">
                <i class="bx bx-chevron-right"></i>
                Полимеры
            </span>
            <div class="tabs-items">
                {% for polymer in bd_polymers %}
                    <span class="btn" data-target="polymer_{{ polymer.id }}">{{ polymer.name }}</span>
                {% endfor %}
            </div>
			<!-- Прочее -->
            <span class="inner-tab">
                <i class="bx bx-chevron-right"></i>
                Прочее
            </span>
            <div class="tabs-items">
                {% for other in bd_others %}
                    <span class="btn" data-target="other_{{ other.id }}">{{ other.name }}</span>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
	</section>

	<section class="content-info">
		<section class="content__table">
			<p class="header">Расходная норма</p>
			<div class="table-main">
				<table class="loaded-table">
					<tr style="background: #5c606a">
						<td>Название соли</td>
						<td>Плотность раствора, г/см³</td>
						<td>Расход соли, кг/м³</td>
						<td>Расход пресной воды, л/м³</td>
					</tr>
				
					{% for salt_name, elem in random_solutions.items %}
						{% if salt_name == "NaCl" or salt_name == "MgCl2" or salt_name == "NH4Cl" %}
						<tr
							id="{{ elem.salt.name }}"
							style="background: {% if forloop.counter|divisibleby:2 %}#363a47{% else %}#292e3c{% endif %}; display:table-row;"
						>
							<td>{{ elem.salt.name }}</td>
							<td>{{ elem.density }}</td>
							<td>{{ elem.salt_consumption }}</td>
							<td>{{ elem.water_consumption }}</td>
						</tr>
						{% endif %}
					{% endfor %}
				</table>
				

				<table class="changed-table">
    <thead>
        <tr style="background: #5c606a">
            <td>Название соли</td>
            <td class="density-header" style="cursor: pointer;">Плотность раствора, г/см³</td>
            <td>Расход соли, кг/м³</td>
            <td>Расход пресной воды, л/м³</td>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<!-- Модальное окно для установки плотности -->
<div class="modal-overlay" id="density-modal-overlay" style="display:none;">
    <div class="modal-window">
		<div class="container-fill-density">
        <h2 class = "fill-density">Заполнить все плотности</h2>
		
		</div>
        <!-- Поле для ввода плотности -->
		<div class="container-for-input">
        <input class = "density-modal-input" type="number" step="0.01" id="mass-density-input" placeholder="Введите плотность" />
		</div>
        
    </div>
</div>
			</div>
			<section class="salt-base-graph">
				<div class="select_container">
					<select
						placeholder="График расхода соли"
						id="graph_select"
						class="graph_select"
					>
						<option id="pressure_graph" value="pressure_graph">
							График расхода соли
						</option>
						<option id="salt_choose_graph" value="salt_choose_graph">
							График вязкости
						</option>
					</select>
				</div>
				<div
					class="plotly-graph"
					id="plotly-graph"
					style="width: 100%; height: 100%"
				></div>
				<div
					class="plotly-graph-changed"
					id="plotly-graph-changed"
					style="width: 100%; height: 100%"
				></div>
			</section>
		</section>
	</section>
	<section class="content__features" style="display: none">
		<p class="header">Свойства жидкости</p>
		{% for salt in bd_names_salts %}
		<table id="{{ salt.name }}" class="salt_table">
			<tr>
				<td class="left-td">Название</td>
				<td>
					<p>{{ salt.name }}</p>
				</td>
			</tr>

			<tr>
				<td class="left-td">Мин. плотность ЖГ, г/см³</td>
				<td>
					<p>{{ salt.min_density }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Макс. плотность ЖГ, г/см³</td>
				<td>
					<p>{{ salt.max_density }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Описание</td>
				<td>
					<p>{{ salt.description }}</p>
				</td>
			</tr>
			{% if salt.note %}
			<tr>
				<td class="left-td">Примечание</td>
				<td>
					<p>{{ salt.note }}</p>
				</td>
			</tr>
			{% endif %}
		</table>
		{% endfor %}


		{% for pav in bd_pavs %}
		<table id="pav_{{ pav.id }}" class="salt_table">	
			<tr>
				<td class="left-td">Название</td>
				<td>
					<p>{{ pav.name }}</p>
				</td>
			</tr>

			<tr>
				<td class="left-td">Тип</td>
				<td>
					<p>{{ pav.type }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Примечание</td>
				<td>
					<p>{{ pav.application }}</p>
				</td>
			</tr>
		</table>
		{% endfor %}

		{% for ingcorr in bd_ingcorrs %}
		<table id="ingcorr_{{ ingcorr.id }}" class="salt_table">	
			<tr>
				<td class="left-td">Название</td>
				<td>
					<p>{{ ingcorr.name }}</p>
				</td>
			</tr>

			<tr>
				<td class="left-td">Тип</td>
				<td>
					<p>{{ ingcorr.type }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Примечание</td>
				<td>
					<p>{{ ingcorr.application }}</p>
				</td>
			</tr>
		</table>
		{% endfor %}

		{% for ingsalt in bd_ingsalts %}
		<table id="ingsalt_{{ ingsalt.id }}" class="salt_table">	
			<tr>
				<td class="left-td">Название</td>
				<td>
					<p>{{ ingsalt.name }}</p>
				</td>
			</tr>

			<tr>
				<td class="left-td">Тип</td>
				<td>
					<p>{{ ingsalt.type }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Примечание</td>
				<td>
					<p>{{ ingsalt.application }}</p>
				</td>
			</tr>
		</table>
		{% endfor %}

		{% for weight in bd_weights %}
		<table id="weight_{{ weight.id }}" class="salt_table">	
			<tr>
				<td class="left-td">Название</td>
				<td>
					<p>{{ weight.name }}</p>
				</td>
			</tr>

			<tr>
				<td class="left-td">Тип</td>
				<td>
					<p>{{ weight.type }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Примечание</td>
				<td>
					<p>{{ weight.application }}</p>
				</td>
			</tr>
		</table>
		{% endfor %}

		{% for polymer in bd_polymers %}
		<table id="polymer_{{ polymer.id }}" class="salt_table">	
			<tr>
				<td class="left-td">Название</td>
				<td>
					<p>{{ polymer.name }}</p>
				</td>
			</tr>

			<tr>
				<td class="left-td">Тип</td>
				<td>
					<p>{{ polymer.type }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Примечание</td>
				<td>
					<p>{{ polymer.application }}</p>
				</td>
			</tr>
		</table>
		{% endfor %}

		{% for other in bd_others %}
		<table id="other_{{ other.id }}" class="salt_table">	
			<tr>
				<td class="left-td">Название</td>
				<td>
					<p>{{ other.name }}</p>
				</td>
			</tr>

			<tr>
				<td class="left-td">Тип</td>
				<td>
					<p>{{ other.type }}</p>
				</td>
			</tr>
			<tr>
				<td class="left-td">Примечание</td>
				<td>
					<p>{{ other.application }}</p>
				</td>
			</tr>
		</table>
		{% endfor %}
	</section>
</main>
{% endblock %}